# Generated by Django 5.0.6 on 2024-07-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('dashboard_users', '0004_examen_alter_inscripcionexamen_examen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examen',
        ),
    ]
