# Generated by Django 5.0.4 on 2024-06-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('opcion1', models.CharField(max_length=200)),
                ('opcion2', models.CharField(max_length=200)),
                ('opcion3', models.CharField(max_length=200)),
                ('opcion4', models.CharField(max_length=200)),
                ('opcion5', models.CharField(max_length=200)),
                ('opcion_correcta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField()),
                ('aprobado', models.BooleanField()),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.examen')),
            ],
        ),
    ]
