# Generated by Django 5.0.6 on 2024-07-31 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del examen')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='usuarios',
            field=models.ManyToManyField(through='dashboard_users.InscripcionExamen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('respuesta1', models.CharField(max_length=255)),
                ('respuesta2', models.CharField(max_length=255)),
                ('respuesta3', models.CharField(max_length=255)),
                ('respuesta4', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(choices=[('1', 'Respuesta 1'), ('2', 'Respuesta 2'), ('3', 'Respuesta 3'), ('4', 'Respuesta 4')], max_length=1)),
                ('orden', models.IntegerField()),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='dashboard_users.examen')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluida', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.examen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.pregunta')),
            ],
        ),
    ]
