# Generated by Django 5.0.6 on 2024-07-12 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionexamen',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('respuesta_correcta', models.CharField(max_length=255, verbose_name='Respuesta correcta')),
                ('respuesta1', models.CharField(max_length=255, verbose_name='Respuesta 1')),
                ('respuesta2', models.CharField(max_length=255, verbose_name='Respuesta 2')),
                ('respuesta3', models.CharField(max_length=255, verbose_name='Respuesta 3')),
                ('respuesta4', models.CharField(max_length=255, verbose_name='Respuesta 4')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='dashboard_users.examen')),
            ],
        ),
    ]
