# Generated by Django 5.0.6 on 2024-07-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='campo_temporal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
