# Generated by Django 5.0.6 on 2024-07-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0002_inscripcionexamen_fecha_inscripcion_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='examen',
        ),
    ]
