# Generated by Django 5.0.6 on 2024-07-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0002_pregunta_campo_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='campo_temporal',
        ),
    ]
