# Generated by Django 5.0.6 on 2024-07-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0003_remove_pregunta_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluida', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.examen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.pregunta')),
            ],
        ),
    ]
