# Generated by Django 5.0.6 on 2024-07-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0003_remove_question_choices_remove_exam_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del examen')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('usuarios', models.ManyToManyField(through='dashboard_users.InscripcionExamen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='inscripcionexamen',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.examen'),
        ),
    ]
