# Generated by Django 5.0.6 on 2024-09-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0002_alter_pregunta_examen_userexam'),
        ('dashboard_users', '0003_remove_pregunta_campo_temporal'),
    ]

    operations = [
    ]
