# Generated by Django 5.0.6 on 2024-07-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0004_exclusionpregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='es_correcta1',
            field=models.BooleanField(default=False, verbose_name='Es correcta 1'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='es_correcta2',
            field=models.BooleanField(default=False, verbose_name='Es correcta 2'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='es_correcta3',
            field=models.BooleanField(default=False, verbose_name='Es correcta 3'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='es_correcta4',
            field=models.BooleanField(default=False, verbose_name='Es correcta 4'),
        ),
    ]
