# Generated by Django 5.0.6 on 2024-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0005_userexam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexam',
            old_name='finalizacion',
            new_name='fecha_envio',
        ),
        migrations.AddField(
            model_name='userexam',
            name='respuestas',
            field=models.JSONField(default=dict),
        ),
    ]
