# Generated by Django 5.0.6 on 2024-09-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0004_merge_20240907_0219'),
        ('dashboard_users', '0005_userexam_delete_exclusionpregunta'),
    ]

    operations = [
    ]
