# Generated by Django 5.0.6 on 2024-07-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0005_remove_pregunta_respuesta_correcta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='es_correcta1',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='es_correcta2',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='es_correcta3',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='es_correcta4',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Respuesta 1'), (2, 'Respuesta 2'), (3, 'Respuesta 3'), (4, 'Respuesta 4')], default=1, verbose_name='Respuesta correcta'),
            preserve_default=False,
        ),
    ]
