# Generated by Django 5.0.6 on 2024-07-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0006_remove_pregunta_es_correcta1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Respuesta 1'), (2, 'Respuesta 2'), (3, 'Respuesta 3'), (4, 'Respuesta 4')], default=1, verbose_name='Respuesta correcta'),
        ),
    ]
