# Generated by Django 5.0.6 on 2024-07-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0007_alter_pregunta_respuesta_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Respuesta 1'), (2, 'Respuesta 2'), (3, 'Respuesta 3'), (4, 'Respuesta 4')], verbose_name='Respuesta correcta'),
        ),
    ]
