# Generated by Django 5.0.6 on 2024-07-30 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0008_pregunta_orden_alter_pregunta_respuesta_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='dashboard_users.examen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.CharField(choices=[('1', 'Respuesta 1'), ('2', 'Respuesta 2'), ('3', 'Respuesta 3'), ('4', 'Respuesta 4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(),
        ),
    ]
